#!/usr/bin/env python3
from math import sqrt
from sys import argv

#Factorizes a number into a product of two smaller numbers.

def factorize():
    '''
      Open the file issued as the first argument
      perform factorization.
    '''
    with open(argv[1]) as f:
        for number in f:
            num = int(number)
            print("{:d}=".format(num), end="")
	    #Check if the number can be factored into 2 and another factor
            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue
	   #evaluate up to the square root since we are looking for the
           #product of 2 small numbers.
            square_r = int(sqrt(num))
            if square_r % 2 == 0:
                square_r += 1
	    #Start checkng from factor 3 since 1 and 2 are already catered for
            for i in range(3, square_r + 1, 2):
                if num % i == 0:
                    print("{}*{}".format(num//i, i))
                    break
            if num % i != 0:
                print("{}={}*1".format(num, num))


factorize()