#! /usr/bin/env python3
from sys import argv


def factorize():
    with open(argv[1]) as f:
        for number in f:
            num = int(number)
            for i in range(2, int(num), 1):
                if num % i == 0:
                    print("{:d}={}*{}".format(num, num // i, i))
                    break


if __name__ == "__main__":
    factorize()
